behaviors:
  PenguinLearning:
    trainer_type: ppo
    summary_freq: 5000
    time_horizon: 128
    max_steps: 1.0e6
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      beta: 1.0e-2
    network_settings:
      hidden_units: 256

# Add this section
environment_parameters:
  my_environment_parameter:
    curriculum:
      - name: default
        completion_criteria:
          measure: reward
          signal_smoothing: true
          min_lesson_length: 80
        value: 0.0
          #thresholds: [-0.1, 0.7, 1.7, 1.7, 1.7, 2.7, 2.7]
          #parameters:
          #  fish_speed: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
          #  feed_radius: [6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.5, 0.2]